# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_auto_20160214_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='approx_time',
            field=models.IntegerField(null=True),
        ),
    ]
